### ISSUE TITLE
Running `dexy viewer` yields an error page

### ISSUE THREAD

**Issue by stephenhay** [dexy/dexy#74] opened 2013-09-04 16:32 UTC
Running `dexy viewer` using dexy 0.9.9.6d in e.g. https://github.com/stephenhay/rdw-code-examples/tree/master/ch11-design-guidelines should provide the viewer at http://localhost:8090/ but instead of the viewer an error is shown.

![image](https://f.cloud.github.com/assets/473099/1081964/9b4c9cb6-157f-11e3-99fb-09d19a0f70ce.png)

**Comment by ananelson** [comment] 2013-09-05 04:41
Duplicate of https://github.com/ananelson/dexy-viewer/issues/1 fixed in dexy-viewer source.

**Closed as completed by ananelson** 2013-09-05 04:41 UTC
